### ISSUE TITLE
Ordering versus equality

### ISSUE THREAD

**Issue by frensjan** [grantjenks/sorted_containers#52]
The implementation of SortedList seems to assume that when items order equally they are actually equal, while that should IMHO not be the case. At least it isn't the case with normal python lists.

My use case is using SortedSet as a queue with ordered traversal (unlike what a heap supports), fast removal (not in order but like set.remove or set.discard) and containment testing. In this use case I have tasks with priorities which may be equal for different tasks. These task objects are sortable (they implement ```__lt__``` and ```__gt__```) based on said priority.

---

However, this usage of SortedSet (and SortedList which is used underneath) fails because of the assumption mentioned earlier. To illustrate, the following test fails in all cases:
```python
from sortedcontainers import SortedList, SortedSet
import unittest


class WithPriority(object):
    def __init__(self, id, priority):
        self.id = id
        self.priority = priority

    def __lt__(self, other):
        return self.priority < other.priority

    def __gt__(self, other):
        return self.priority > other.priority

    def __repr__(self):
        return '<WithPriority %r %r>' % (self.id, self.priority)


a = WithPriority(0, 1)
b = WithPriority(1, 1)


class OrderingVsPriorityTest(unittest.TestCase):
    def test_list_index(self):
        c = SortedList((a, b))
        self.assertEqual(b, c[c.index(b)])

    def test_list_contains(self):
        c = SortedList((a, b))
        self.assertIn(b, c)

    def assert_remove_correct(self, container, op):
        c = container((a, b))
        op(c, b) # trips up list_remove and set_remove
        self.assertIn(a, c)
        self.assertNotIn(b, c)
        self.assertEqual(1, len(c)) # trips up list_discard
        self.assertEqual(1, sum(1 for _ in c)) # trips up set_discard

    def test_list_discard(self):
        self.assert_remove_correct(SortedList, SortedList.discard)

    def test_list_remove(self):
        self.assert_remove_correct(SortedList, SortedList.remove)

    def test_set_discard(self):
        self.assert_remove_correct(SortedSet, SortedSet.discard)

    def test_set_remove(self):
        self.assert_remove_correct(SortedSet, SortedSet.remove)
```

The failures are:
```
Finding files... done.
Importing test modules ... done.

======================================================================
ERROR: test_list_index (sortedlist_prios_test.EqualityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/frens-jan/Workspaces/ext/sorted_containers/sortedlist_prios_test.py", line 26, in test_list_index
    self.assertEqual(b, c[c.index(b)])
  File "/home/frens-jan/Workspaces/ext/sorted_containers/sortedcontainers/sortedlist2.py", line 1259, in index
    raise ValueError('{0} is not in list'.format(repr(val)))
ValueError: <WithPriority 1 1> is not in list

======================================================================
ERROR: test_list_remove (sortedlist_prios_test.EqualityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/frens-jan/Workspaces/ext/sorted_containers/sortedlist_prios_test.py", line 44, in test_list_remove
    self.assert_remove_correct(SortedList, SortedList.remove)
  File "/home/frens-jan/Workspaces/ext/sorted_containers/sortedlist_prios_test.py", line 34, in assert_remove_correct
    op(c, b) # trips up list_remove and set_remove
  File "/home/frens-jan/Workspaces/ext/sorted_containers/sortedcontainers/sortedlist2.py", line 262, in remove
    raise ValueError('{0} not in list'.format(repr(val)))
ValueError: <WithPriority 1 1> not in list

======================================================================
ERROR: test_set_remove (sortedlist_prios_test.EqualityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/frens-jan/Workspaces/ext/sorted_containers/sortedlist_prios_test.py", line 50, in test_set_remove
    self.assert_remove_correct(SortedSet, SortedSet.remove)
  File "/home/frens-jan/Workspaces/ext/sorted_containers/sortedlist_prios_test.py", line 34, in assert_remove_correct
    op(c, b) # trips up list_remove and set_remove
  File "/home/frens-jan/Workspaces/ext/sorted_containers/sortedcontainers/sortedset.py", line 199, in remove
    self._list.remove(value)
  File "/home/frens-jan/Workspaces/ext/sorted_containers/sortedcontainers/sortedlist2.py", line 262, in remove
    raise ValueError('{0} not in list'.format(repr(val)))
ValueError: <WithPriority 1 1> not in list

======================================================================
FAIL: test_list_contains (sortedlist_prios_test.EqualityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/frens-jan/Workspaces/ext/sorted_containers/sortedlist_prios_test.py", line 30, in test_list_contains
    self.assertIn(b, c)
AssertionError: <WithPriority 1 1> not found in SortedList([<WithPriority 0 1>, <WithPriority 1 1>], load=1000)

======================================================================
FAIL: test_list_discard (sortedlist_prios_test.EqualityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/frens-jan/Workspaces/ext/sorted_containers/sortedlist_prios_test.py", line 41, in test_list_discard
    self.assert_remove_correct(SortedList, SortedList.discard)
  File "/home/frens-jan/Workspaces/ext/sorted_containers/sortedlist_prios_test.py", line 37, in assert_remove_correct
    self.assertEqual(1, len(c)) # trips up list_discard
AssertionError: 1 != 2

======================================================================
FAIL: test_set_discard (sortedlist_prios_test.EqualityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/frens-jan/Workspaces/ext/sorted_containers/sortedlist_prios_test.py", line 47, in test_set_discard
    self.assert_remove_correct(SortedSet, SortedSet.discard)
  File "/home/frens-jan/Workspaces/ext/sorted_containers/sortedlist_prios_test.py", line 38, in assert_remove_correct
    self.assertEqual(1, sum(1 for _ in c)) # trips up set_discard
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 6 tests in 0.007s

FAILED (failures=3, errors=3)
```

Note that the the SortedSet test cases don't fail consistently, I suspected the python hash seed, but ruled that out by setting PYTHONHASHSEED.

---

I'm using ```SortedSet(key=...)``` to work around the issue above (using SortedListWithKey underneath). Maybe the use case above just isn't suited for SortedSet/List without key ... Feedback on the issue is much appreciated.

**Comment by grantjenks** [comment]
> The implementation of SortedList seems to assume that when items order equally they are actually equal,

That is correct. SortedList expects a [total ordering](https://en.wikipedia.org/wiki/Total_order) though it relies only on `__lt__`. In your example below `a < b`, `a > b`, and `a == b` are all `False` which is not a total ordering.

> while that should IMHO not be the case. At least it isn't the case with normal python lists.

Can you show an example of how Python lists differ? I believe the behavior matches that of Python lists.

SortedList is using the [bisect](https://docs.python.org/2/library/bisect.html) module internally. The documentation for `bisect_left` states:

> If x is already present in a, the insertion point will be before (to the left of) any existing entries.

So I think it is fair of SortedList to expect the insertion index to be before all equal values. As you've observed, SortedListWithKey does not make this assumption and so while keys are equal, it iterates forward searching for value equality. That is why SortedListWithKey was made.

If you can design/modify the `__lt__` method of your objects then you could do the following:

```
class WithPriority(object):
    def __init__(self, priority):
        self.priority = (priority, id(self))

    # __eq__, __ne__, and __hash__ inherited from object, using id(self)

    def __lt__(self, other):
        return self.priority < other.priority

    def __repr__(self):
        return '<WithPriority %s %r>' % (id(self), self.priority)
```

I've removed `self.id` as it was extraneous and, as before, equality and hashing relies on `id(self)`. The priority is now a tuple of the given number and the object's `id`. This will break ties and create a total ordering.

To pass your test cases, I also modified these lines:

```
a = WithPriority(1)
b = WithPriority(1)
```

With those changes, both SortedList and SortedSet can be used without a key function. Note that objects with equal priority will be ordered by their `id`, in CPython that is their memory address which is likely to be chaotic/pseudo-random. You may prefer to use a monotonically increasing counter or real source of randomness.

**Comment by frensjan** [comment]
@grantjenks thanks for the prompt reply and pointing out that a total order is indeed expected. I had a mental model based on a python list and its ```sort``` (or ```bisect.insort```), ```remove``` and ```__contains__``` behavior which - if I'm not mistaken - doesn't require a total ordering. I.e. something primitive like:
```python
class SortedSet(object):
    __slots__ = ('_set', '_list')

    def __init__(self, key=None):
        self._set = set()
        self._list = []
 
    def add(self, value):
        if value not in self._set:
            self._set.add(value)
            insort(self._list, value)
 
    def remove(self, value):
        self._set.remove(value)
        self._list.remove(value)
         
    def discard(self, value):
        try:
            self._set.remove(value)
            self._list.remove(value)
        except (KeyError, ValueError):
            pass
 
    def __contains__(self, value):
        return value in self._set
  
    def __iter__(self):
        return iter(self._list)
      
    def __bool__(self):
        return bool(self._set)
```

I'll give the ```id(...)``` based tie breaking a go. Thanks!

**Comment by grantjenks** [comment]
`sortedcontainers.SortedSet` is like yours except for the `self._list.remove(value)` lines. SortedList does something closer to:

```
index = bisect_left(self._list, value)
if self._list[index] == value:
    del self._list[index]
```

This is only similar to SortedList because SortedContainers uses a segment-list structure to avoid the linear time removal operation.
