### ISSUE TITLE
no attribute bisect_key

### ISSUE THREAD

**Issue by Tjorriemorrie** [grantjenks/sorted_containers#58]
```
2016-12-06 20:13:09,061 - INFO    - [p.py:dist_player_stats] dist = SortedDict(None, 1000, {0: 'f', 0.749: 'f', 0.75: 'f', 0.874: 's', 0.875: 's', 0.999: 'l', 1.0: 'a'})
2016-12-06 20:13:09,062 - DEBUG   - [p.py:dist_player_stats] dist = <class 'sortedcontainers.sorteddict.SortedDict'>
2016-12-06 20:13:09,062 - DEBUG   - [p.py:dist_player_stats] i = 0.0
2016-12-06 20:13:09,062 - ERROR   - [retrace.py:__call__] Caught exception when calling __main__.play
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/retrace.py", line 289, in __call__
    result = fn(*args, **kwargs)
  File "/code/p.py", line 1552, in play
    r = repr(self.engine)
  File "/code/p.py", line 337, in __repr__
    dist_stats = ES.dist_player_stats(d['stats'], True)
  File "/code/p.py", line 198, in dist_player_stats
    k = dist.bisect_key(i)
AttributeError: 'SortedDict' object has no attribute 'bisect_key'
```

**Comment by Tjorriemorrie** [comment]
ok, so no key present.

Why not just always use operator.pos? Is there a performance issue to this?

**Comment by grantjenks** [comment]
Right, if you do not initialize SortedDict with a key-function then the key-specific methods like ``bisect_key``, etc. are missing from the object. Simply use ``bisect`` instead.

I do not see how ``operator.pos`` would help SortedDict here.
