### ISSUE TITLE
SortedDict can not handle key argument when using non-strings as keys

### ISSUE THREAD

**Issue by jogc** [grantjenks/sorted_containers#90]
```
$ pip show sortedcontainers | grep Version
Version: 1.5.10

$ python3 --version
Python 3.6.5

$ python3
Python 3.6.5 (default, May  6 2018, 09:42:08) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sortedcontainers
>>> s=sortedcontainers.SortedDict({'a':'one','b':'two'})
>>> s=sortedcontainers.SortedDict({'a':'one','b':'two'}, key=str.upper)
>>> s=sortedcontainers.SortedDict({0:'one',1:'two'})
>>> s=sortedcontainers.SortedDict({0:'one',1:'two'}, key=int)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/X/env/lib/python3.6/site-packages/sortedcontainers/sorteddict.py", line 140, in __init__
    self._update(*args, **kwargs)
  File "/Users/X/env/lib/python3.6/site-packages/sortedcontainers/sorteddict.py", line 339, in update
    self._list_update(self._iter())
  File "/Users/X/env/lib/python3.6/site-packages/sortedcontainers/sortedlist.py", line 190, in update
    values = sorted(iterable)
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by grantjenks** [comment]
Your keyword argument is not working like you expect. Put the key first as a positional argument.

See the end of the SortedDict section in the introduction for an example: http://www.grantjenks.com/docs/sortedcontainers/introduction.html
